//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "realtor_object")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub phone: String,
    pub full_name: String,
    pub metro_station: String,
    #[sea_orm(column_type = "Float")]
    pub metro_distance: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::picture::Entity")]
    Picture,
}

impl Related<super::picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Picture.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
